#spring:
#  config:
#    activate:
#      on-profile: develop
---
spring:
  config:
    activate:
      on-profile: develop
  thymeleaf:
    cache: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/demo_db
    username: user
    password: password
    ### 初期化を行うかの指定。
    initialization-mode: always
  ### スネークケースのDBカラム名をSpringのEntity側ではキャメルケースとして対応付けてくれる。
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
# SQLSQLログ出力
logging:
  level:
    org:
      springframework: WARN
    com:
      example:
        demo:
          repository: DEBUG
          UserDataMapper: DEBUG
#    mapper-locations:
#      classpath*:com/example/demo/dao/*.xml:
  jpa:
    properties:
      hibernate:
        dialect=org:
          hibernate:
            dialect:
              MySQL5InnoDBDialect:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    web:
      base-path: /

---
#spring:
#  profiles: production
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://xxxx:3306/demo_db
#    username: xxxx
#    password: xxxx
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  data:
#    web:
#      base-path: /