version: "3.8"

x-template: &flyway-template
  build: ./flyway
  volumes:
    - ./flyway/sql:/flyway/sql
    - ./flyway/conf:/flyway/conf
  depends_on:
    - db
  profiles:
    - flyway
volumes:
  mysql-db:
    driver: local
services:
  flyway-baseline:
    <<: *flyway-template
    command: baseline

  flyway-clean:
    <<: *flyway-template
    command: clean

  flyway-migrate:
    <<: *flyway-template
    command: migrate

  flyway-info:
    <<: *flyway-template
    command: info

  flyway-repair:
    <<: *flyway-template
    command: repair

  db:
    build: ./mysql
    image: demo-db:0.0.1
    # コンテナ名を明示的に指定する
    container_name: db-container
    # ホスト名を明示的に指定する
    hostname: db-server
    restart: always
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ../log/mysql:/var/log/mysql
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  app:
    build: ./java
    image: demo-app:0.0.1
    # コンテナ名を明示的に指定する
    container_name: app-container
    # ホスト名を明示的に指定する
    hostname: app-server
    volumes:
      - ../:/app
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db
    command: ./gradlew clean bootRun
